### ISSUE TITLE
UI Button and Vague Description Settings Button Do Nothing

### ISSUE THREAD

**Issue by Armandeus66** [WBHarry/pf2e-bestiary-tracking#36]
1. After clicking the crablike UI button, nothing happens and this appears in the console.
```
Uncaught (in promise) TypeError: undefined. Cannot set properties of undefined (setting 'playerBased')
[Detected 1 package: pf2e-bestiary-tracking(0.8.7.2)]
    at PF2EBestiary._prepareContext (bestiary.js:250:56)
    at async #render (foundry-esm.js:44319:23)
    at async Semaphore._try (foundry-esm.js:6645:19)
```
2. When clicking Vague Description Settings in the settings menu, nothing happens and this appears in the console.
```
vagueDescriptionsMenu.js:10 Uncaught TypeError: undefined. Cannot convert undefined or null to object
[Detected 1 package: pf2e-bestiary-tracking(0.8.7.2)]
    at Function.keys (<anonymous>)
    at new VagueDescriptionsMenu (vagueDescriptionsMenu.js:10:29)
    at ExtendedSettingsConfig._onClickSubmenu (foundry.js:86573:17)
    at HTMLButtonElement.dispatch (jquery.min.js:2:40035)
    at v.handle (jquery.min.js:2:38006)
```
(Foundry VTT 12.331, PF2E 6.2.2, Chrome)

**Comment by WBHarry** [comment]
Some oddities that crept in with failed migrations. I just released v0.8.8, and I do think it should resolve these problems.
If you have the opportunity to update, do tell if it worked 🙈

**Comment by ngPescado** [comment]
Running the same versions as OP (all other mods disabled) coming from older version with populated bestiary. Update lost functionality to open. Clean uninstall of mod then reinstall still no resolution. Similar console logs as OP  ...

> bestiary.js:261 Uncaught (in promise) TypeError: undefined. usedTypes is not iterable
> [Detected 1 package: pf2e-bestiary-tracking(0.8.8)]
>     at bestiary.js:261:33
>     at Array.reduce (<anonymous>)
>     at PF2EBestiary.prepareBestiary (bestiary.js:252:52)
>     at PF2EBestiary._prepareContext (bestiary.js:292:33)
>     at async #render (foundry-esm.js:44319:23)
>     at async Semaphore._try (foundry-esm.js:6645:19)

I refreshed the Bestiary Labels on update as advised in Discord and they filled correctly. Migration issue possibly? Figured an uninstall would have removed anything since the database is just a JSON structure, right? What am I missing?

**Comment by ngPescado** [comment]
Just updated to 0.8.8.1 and caught an error on server start up that I missed before ...

> migrationHandler.js:270 Uncaught (in promise) TypeError: undefined. monster.inTypes is not iterable
> [Detected 1 package: pf2e-bestiary-tracking(0.8.8.1)]
>     at migrateBestiary (migrationHandler.js:270:39)
>     at async handleDataMigration (migrationHandler.js:75:9)

hopefully sheds more light ...

**Comment by ngPescado** [comment]
Created new world, worked perfectly (with both 0.8.8.1 and the new 0.8.8.2), still same errors on old world. Even worked on fresh Starfinder 2e world (pf2e with mod activated). Old world (where issue persists) is a very long standing game updated through multiple versions of Foundry (since v10) and PF2e with dozens of mods being added/removed over time. The game is also Abomination Vaults and not all content  has updated ... I still have a random error from a non-supported creature with "Magic Missile" references deep in the system. Game is almost finished so I haven't nuked the world but I could definitely imagine ghosts in the machine for this world. May not be worth wracking brain cells over for the old old installs.

**Comment by ngPescado** [comment]
VICTORY 0.8.8.3 solved it ... wipe of the data seems to have repaired the problem. Will continue to test but it looks good on this end. Hopefully, the OP will have the same results and give thumbs up to close this ticket.

**Comment by WBHarry** [comment]
Huzzah. 🥳 
Yeah, sad about the data loss, but there were some important considerations I hadn't taken in the early versions that needed to be there going forward. So a bit of a ripped bandaid.

**Comment by Armandeus66** [comment]
Thanks for working on this! I will test it in a few hours and reply then.
